/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 AzaleaTransformed.glb --transform -d 
Files: AzaleaTransformed.glb [5.33MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\AzaleaTransformed-transformed.glb [5.14MB] (4%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/AzaleaTransformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Azalea_Leaves.geometry} material={materials['minecraft_block-flowering_azalea_leaves']} />
      <mesh geometry={nodes['minecraft_block-azalea_plant'].geometry} material={materials['minecraft_block-flowering_azalea_top']} />
      <mesh geometry={nodes['minecraft_block-azalea_plant_1'].geometry} material={materials['minecraft_block-azalea_plant']} />
    </group>
  )
}

