/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BridgeTransformed.glb --transform -d 
Files: BridgeTransformed.glb [2.4MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\BridgeTransformed-transformed.glb [2.11MB] (12%)
*/

import React, { use } from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/BridgeTransformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['minecraft_block-lantern002'].geometry} material={materials.Mangrove_trapdoor} />
      <mesh geometry={nodes['minecraft_block-lantern002_1'].geometry} material={materials.Stone_walls} />
      <mesh geometry={nodes['minecraft_block-lantern002_2'].geometry} material={materials.Stone_brick_walls} />
    </group>
  )
}

