/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CampfireTransformed.glb --transform -d 
Files: CampfireTransformed.glb [937.39KB] > C:\Users\xav\Desktop\Minor\Compressed GLB\CampfireTransformed-transformed.glb [906.18KB] (3%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'
import { convertMaterialsToMeshBasicMaterial } from '../utils/convertMaterial'


export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/CampfireTransformed-transformed.glb')
  convertMaterialsToMeshBasicMaterial(materials)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['minecraft_block-campfire_fire'].geometry} material={materials.campfire_fire} />
      <mesh geometry={nodes['minecraft_block-campfire_fire_1'].geometry} material={materials.campfire_stone} />
    </group>
  )
}


