/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CherryTreesTransformed.glb --transform -d 
Files: CherryTreesTransformed.glb [11.31MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\CherryTreesTransformed-transformed.glb [10.4MB] (8%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'
import { convertMaterialsToMeshBasicMaterial } from '../utils/convertMaterial'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/CherryTreesTransformed-transformed.glb')
  convertMaterialsToMeshBasicMaterial(materials)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cherry_Trees_north_1.geometry} material={materials.Cherry_Trees_north_leaves} />
      <mesh geometry={nodes.Cherry_Trees_north_2.geometry} material={materials.Cherry_Trees_north} />
      <mesh geometry={nodes.Cherry_Trees_south_1.geometry} material={materials.Cherry_Trees_south_Leaves} />
      <mesh geometry={nodes.Cherry_Trees_south_2.geometry} material={materials.Cherry_Trees_south} />
    </group>
  )
}

