/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ExtrasTransformed.glb --transform -d 
Files: ExtrasTransformed.glb [3.64MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\ExtrasTransformed-transformed.glb [3.5MB] (4%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/ExtrasTransformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Extras_1.geometry} material={materials.bee_nest_side} />
      <mesh geometry={nodes.Extras_2.geometry} material={materials.cave_vines_lit} />
    </group>
  )
}

