/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Extras3Transformed.glb --transform -d 
Files: Extras3Transformed.glb [2.36MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\Extras3Transformed-transformed.glb [2.28MB] (4%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/Extras3Transformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Dirt_Path.geometry} material={materials['Dirt_path.002']} />
      <mesh geometry={nodes.Water.geometry} material={materials['minecraft_block-water_flow.001']} />
    </group>
  )
}


