/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Extras2Transformed.glb --transform -d 
Files: Extras2Transformed.glb [5.11MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\Extras2Transformed-transformed.glb [4.42MB] (14%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/Extras2Transformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Moss.geometry} material={materials.Moss} />
      <mesh geometry={nodes.pink_petals.geometry} material={materials['minecraft_block-pink_petals.001']} />
      <mesh geometry={nodes['minecraft_block-wheat_stage7'].geometry} material={materials['minecraft_block-wheat_stage7']} />
      <mesh geometry={nodes['minecraft_block-wheat_stage7_1'].geometry} material={materials['minecraft_block-farmland_moist']} />
    </group>
  )
}


