/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 GrassTransformed.glb --transform -d 
Files: GrassTransformed.glb [5.87MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\GrassTransformed-transformed.glb [5.15MB] (12%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/GrassTransformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.short_grass.geometry} material={materials['minecraft_block-short_grass.001']} />
      <mesh geometry={nodes.Tall_grass.geometry} material={materials['minecraft_block-tall_grass_bottom.001']} />
    </group>
  )
}


