/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 GroundSouthTransformed.glb --transform -d 
Files: GroundSouthTransformed.glb [2.72MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\GroundSouthTransformed-transformed.glb [2.43MB] (11%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/GroundSouthTransformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grass_dirt_south.geometry} material={materials['Grass_dirt_south.002']} />
    </group>
  )
}

