/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HouseTransformed.glb --transform -d 
Files: HouseTransformed.glb [1.23MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\HouseTransformed-transformed.glb [1.2MB] (3%)
*/

import React from 'react'
import useGLTFWithKTX2 from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/HouseTransformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['minecraft_block-oak_planks002'].geometry} material={materials['minecraft_block-glass']} />
      <mesh geometry={nodes['minecraft_block-oak_planks002_1'].geometry} material={materials.HouseOakplank} />
    </group>
  )
}


