/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MuseumInteriorTransformed.glb --transform -d 
Files: MuseumInteriorTransformed.glb [2.32MB] > C:\Users\xav\Downloads\MuseumInteriorTransformed-transformed.glb [1.92MB] (17%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2 from '../utils/useGLTFWithKTX'
import { convertMaterialsToMeshBasicMaterial } from '../utils/convertMaterial'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/MuseumInteriorTransformed-transformed.glb')

convertMaterialsToMeshBasicMaterial(materials)

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.092]}>
        <mesh geometry={nodes['minecraft_painting-pigscene002'].geometry} material={materials.D1} />
        <mesh geometry={nodes['minecraft_painting-pigscene002_1'].geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.S1Painting4.geometry} material={materials.Xavier1} />
      <mesh geometry={nodes.S2Painting1.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.S2Painting2.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.S2painting3.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.S2Painting4.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.S3Painting1.geometry} material={materials['Material.016']} />
      <mesh geometry={nodes.S3Painting2.geometry} material={materials['Material.019']} />
      <mesh geometry={nodes.S3Painting3.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.S3Painting4.geometry} material={materials['Material.021']} />
      <mesh geometry={nodes['minecraft_entity-signs-cherry'].geometry} material={materials.Material} />
      <mesh geometry={nodes['minecraft_entity-signs-cherry_1'].geometry} material={materials['minecraft_entity-signs-cherry']} />
      <mesh geometry={nodes['minecraft_entity-signs-cherry_2'].geometry} material={materials['minecraft_block-chain.001']} />
      <mesh geometry={nodes['minecraft_painting-orb002'].geometry} material={materials['Material.001']} />
      <mesh geometry={nodes['minecraft_painting-orb002_1'].geometry} material={materials.per1} />
      <mesh geometry={nodes['minecraft_painting-burning_skull002'].geometry} material={materials['Material.002']} />
      <mesh geometry={nodes['minecraft_painting-burning_skull002_1'].geometry} material={materials.Ayoub1} />
    </group>
  )
}


