/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MuseumExteriorTransformed.glb --transform -d 
Files: MuseumExteriorTransformed.glb [3.38MB] > C:\Users\xav\Downloads\MuseumExteriorTransformed-transformed.glb [2.75MB] (19%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2 from '../utils/useGLTFWithKTX'
import { convertMaterialsToMeshBasicMaterial } from '../utils/convertMaterial'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/MuseumExteriorTransformed-transformed.glb')

  convertMaterialsToMeshBasicMaterial(materials)

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['minecraft_block-stripped_pale_oak_log'].geometry} material={materials['minecraft_block-stripped_pale_oak_log']} />
      <mesh geometry={nodes['minecraft_block-stripped_pale_oak_log_1'].geometry} material={materials['minecraft_block-pale_oak_trapdoor']} />
    </group>
  )
}


