/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MuseumGebouwTransformed.glb --transform -d 
Files: MuseumGebouwTransformed.glb [1.44MB] > C:\Users\xav\Downloads\MuseumGebouwTransformed-transformed.glb [565.33KB] (61%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2 from '../utils/useGLTFWithKTX'
import { convertMaterialsToMeshBasicMaterial } from '../utils/convertMaterial'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/MuseumGebouwTransformed-transformed.glb')
  convertMaterialsToMeshBasicMaterial(materials)
  return (
    <group {...props} dispose={null}>
      <group position={[-52.474, 36.832, 10.909]} rotation={[0, 0.01, Math.PI]}>
        <group position={[-0.106, 0.661, 0]}>
          <mesh geometry={nodes.Left_Leg.geometry} material={materials.Villager} position={[-52.471, 36.171, -10.403]} rotation={[0, 0.01, -Math.PI]} />
        </group>
        <group position={[0.106, 0.661, 0]}>
          <mesh geometry={nodes.Right_Leg.geometry} material={materials.Villager} position={[-52.682, 36.171, -10.403]} rotation={[0, 0.01, -Math.PI]} />
        </group>
        <group position={[0, -0.343, 0.131]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Head.geometry} material={materials.Villager} position={[-52.577, 10.533, 37.175]} rotation={[Math.PI / 2, 0.01, Math.PI]} />
        </group>
        <mesh geometry={nodes.Body.geometry} material={materials.Villager} position={[-52.577, 36.832, -10.403]} rotation={[0, 0.01, -Math.PI]} />
      </group>
      <mesh geometry={nodes.chiseled_quartz_block.geometry} material={materials['minecraft_block-chiseled_quartz_block.001']} />
      <mesh geometry={nodes.end_rod.geometry} material={materials['minecraft_block-end_rod']} />
      <mesh geometry={nodes.MuseumCobblestone.geometry} material={materials.MuseumCobble} />
      <mesh geometry={nodes.MuseumStoneBricks.geometry} material={materials['minecraft_block-stone_bricks.003']} />
      <mesh geometry={nodes.quartz_block.geometry} material={materials['minecraft_block-quartz_block_top.001']} />
      <mesh geometry={nodes.quartz_bricks.geometry} material={materials['minecraft_block-quartz_bricks.001']} />
      <mesh geometry={nodes.quartz_pillar.geometry} material={materials['minecraft_block-quartz_pillar.001']} />
      <mesh geometry={nodes.red_wool.geometry} material={materials['minecraft_block-red_wool.001']} />
      <mesh geometry={nodes.S1Painting4.geometry} material={materials.Xavier1} />
      <mesh geometry={nodes.S2Painting1.geometry} material={materials['Material.007']} />
      <mesh geometry={nodes.S2Painting2.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.S2painting3.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.S2Painting4.geometry} material={materials['Material.013']} />
      <mesh geometry={nodes.S3Painting1.geometry} material={materials['Material.016']} />
      <mesh geometry={nodes.S3Painting3.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.white_candle_lit.geometry} material={materials['minecraft_block-white_candle_lit.001']} />
      <mesh geometry={nodes.white_stained_glass.geometry} material={materials['minecraft_block-white_stained_glass.001']} />
      <mesh geometry={nodes['minecraft_block-chain001'].geometry} material={materials['minecraft_block-chain.001']} />
      <mesh geometry={nodes['minecraft_block-chain001_1'].geometry} material={materials['Bridge.001']} />
      <mesh geometry={nodes['minecraft_block-cave_vines_lit001'].geometry} material={materials.lectern_top} />
      <mesh geometry={nodes['minecraft_block-cave_vines_lit001_1'].geometry} material={materials.lectern_base} />
      <mesh geometry={nodes['minecraft_block-cave_vines_lit001_2'].geometry} material={materials.lectern_front} />
      <mesh geometry={nodes['minecraft_block-cave_vines_lit001_3'].geometry} material={materials.lectern_sides} />
      <mesh geometry={nodes['minecraft_block-stripped_pale_oak_log'].geometry} material={materials['minecraft_block-stripped_pale_oak_log']} />
      <mesh geometry={nodes['minecraft_block-stripped_pale_oak_log_1'].geometry} material={materials['minecraft_block-pale_oak_trapdoor']} />
      <mesh geometry={nodes['minecraft_painting-orb002'].geometry} material={materials['Material.001']} />
      <mesh geometry={nodes['minecraft_painting-orb002_1'].geometry} material={materials.per1} />
      <mesh geometry={nodes['minecraft_painting-burning_skull002'].geometry} material={materials['Material.002']} />
      <mesh geometry={nodes['minecraft_painting-burning_skull002_1'].geometry} material={materials.Ayoub1} />
      <mesh geometry={nodes['minecraft_painting-pigscene002'].geometry} material={materials.D1} />
      <mesh geometry={nodes['minecraft_painting-pigscene002_1'].geometry} material={materials['Material.004']} />
      <mesh geometry={nodes['minecraft_entity-signs-cherry'].geometry} material={materials['minecraft_entity-signs-cherry']} />
      <mesh geometry={nodes['minecraft_entity-signs-cherry_1'].geometry} material={materials.Material} />
    </group>
  )
}

