/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 OakTreesTransformed.glb --transform -d 
Files: OakTreesTransformed.glb [5.09MB] > C:\Users\xav\Desktop\Minor\Compressed GLB\OakTreesTransformed-transformed.glb [4.87MB] (4%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import useGLTFWithKTX2  from '../utils/useGLTFWithKTX'

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2('/OakTreesTransformed-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Oak_Trees_1.geometry} material={materials.Oak_tree_logs} />
      <mesh geometry={nodes.Oak_Trees_2.geometry} material={materials.Oak_Leaves} />
    </group>
  )
}


